# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  nanopass = {
    pname = "nanopass";
    version = "f3100cedaf9ed7fb89647a770d855997b32cf17e";
    src = fetchFromGitHub {
      owner = "nanopass";
      repo = "nanopass-framework-scheme";
      rev = "f3100cedaf9ed7fb89647a770d855997b32cf17e";
      fetchSubmodules = false;
      sha256 = "sha256-NsY+V0r/lgycSIVTeHcNjJ398YwEijLlaGySNdTopxw=";
    };
    date = "2022-08-30";
  };
  rough-draft = {
    pname = "rough-draft";
    version = "6a5e64aa325d2fd7ab1e161cfcb45ba2f9a057de";
    src = fetchFromGitHub {
      owner = "akeep";
      repo = "rough-draft";
      rev = "6a5e64aa325d2fd7ab1e161cfcb45ba2f9a057de";
      fetchSubmodules = false;
      sha256 = "sha256-/as+XqStSyHc/vLImmGgowxgVjqi/jITolH9D6AJfek=";
    };
    date = "2023-02-13";
  };
}
