#! /bin/sh

# This file is part of Compact.
# Copyright (C) 2025 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cat $1 > test-center/test.ts
cd test-center
if NPM_CONFIG_UPDATE_NOTIFIER=false npm run test --silent > test.out 2>&1 ; then
  echo success
else
  sed -e 's/\x1B\[[0-9;]*[a-zA-Z]//g' test.out
fi
