// This file is part of Compact.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Standard library statements related grammar.
 *
 * TODO: make grammar more flexible so we can use different grammars together (like common)
 */
const std_grammar = {
    // entry point #1
    single_statements: [
        ['import CompactStandardLibrary;', 'line_separator', 'single_counter', 'statement_declaration', 'single_counter_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'single_set', 'statement_declaration', 'single_set_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'single_map', 'statement_declaration', 'single_map_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'single_list', 'statement_declaration', 'single_list_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'single_mt', 'statement_declaration', 'single_mt_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'single_hmt', 'statement_declaration', 'single_hmt_body'],
        ['import CompactStandardLibrary;', 'line_separator', 'statement_declaration', 'single_kernel_body'],
    ],
    single_kernel_body: [
        ['{\n ', 'no_variable_kernel', 'no_variable_after_statement', '\n}']
    ],
    single_counter: [
        [ 'export ledger var_counter: Counter', 'valid_end_line'],
    ],
    single_counter_body: [
        ['{\n ', 'no_variable_counter', 'no_variable_after_statement', '\n}']
    ],
    single_set: [
        [ 'export ledger var_set: Set<', 'statement_std_types', '>', 'valid_end_line'],  
    ],
    single_set_body: [
        ['{\n ', 'no_variable_set', 'no_variable_after_statement', '\n}']
    ],
    single_map: [
        [ 'export ledger var_map: Map<', 'statement_std_types', ',', 'statement_valid_types', '>', 'valid_end_line'],
    ],
    single_map_body: [
        ['{\n ', 'no_variable_map', 'no_variable_after_statement', '\n}']
    ],
    single_list: [
        [ 'export ledger var_list: List<', 'statement_std_types', '>', 'valid_end_line'],
    ],
    single_list_body: [
        ['{\n ', 'no_variable_list', 'no_variable_after_statement', '\n}']
    ],
    single_mt: [
        [ 'export ledger var_mt: MerkleTree<', '20', ',','statement_std_types', '>', 'valid_end_line'],
    ],
    single_mt_body: [
        ['{\n ', 'no_variable_mt', 'no_variable_after_statement', '\n}']
    ],
    single_hmt: [
        [ 'export ledger var_hmt: HistoricMerkleTree<', '20', ',', 'statement_std_types', '>', 'valid_end_line'],
    ],
    single_hmt_body: [
        ['{\n ', 'no_variable_hmt', 'no_variable_after_statement', '\n}']
    ],
    // entry point #2
    statements: [
        ['import CompactStandardLibrary;', 'line_separator', 'statement_variables', 'statement_declaration', 'statement_body'],
    ],
    statement_variables: [
        [
            'export ledger var_counter: Counter', 'valid_end_line',
            'export ledger var_set: Set<', 'statement_std_types', '>', 'valid_end_line',
            'export ledger var_map: Map<', 'statement_std_types', ',', 'statement_valid_types', '>', 'valid_end_line',
            'export ledger var_list: List<', 'statement_std_types', '>', 'valid_end_line',
            'export ledger var_mt: MerkleTree<', '20', ',','statement_std_types', '>', 'valid_end_line',
            'export ledger var_hmt: HistoricMerkleTree<', '20', ',', 'statement_std_types', '>', 'valid_end_line',
        ],
    ],
    statement_declaration: [['constructor()'], ['export circuit test(): []']],
    statement_body: [['{\n ', 'variable_a', 'variable_b', 'variable_c', 'variable_d', 'statement', 'after_statement', '\n}']],
    variable_a: [
        ['const ', 'bob', ' = ', 'default<', 'statement_valid_types', '>', 'valid_end_line'],
        ['const ', 'bob', ' = ', 'small_random_number', 'valid_end_line'],
    ],
    variable_b: [
        ['const ', 'tom', ' = ', 'default<', 'statement_valid_types', '>', 'valid_end_line'],
        ['const ', 'tom', ' = ', 'small_random_number', 'valid_end_line'],
    ],
    variable_c: [
        ['const ', 'greg', ' = ', 'default<', 'statement_valid_types', '>', 'valid_end_line'],
        ['const ', 'greg', ' = ', 'small_random_number', 'valid_end_line'],
    ],
    variable_d: [
        ['const ', 'adonis', ' = ', 'default<', 'statement_valid_types', '>', 'valid_end_line'],
        ['const ', 'adonis', ' = ', 'small_random_number', 'valid_end_line'],
    ],
    statement: [['kernel'], ['counter'], ['set'], ['map'], ['list'], ['mt'], ['hmt']],
    kernel: [
        ['variable_kernel'], ['no_variable_kernel'] 
    ], 
    variable_kernel: [
        ['optional_statement_variable', 'kernel.checkpoint(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall(bob, tom , greg)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall(bob, tom , greg, adonis)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinReceive(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinReceive(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinSpend(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinSpend(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapNullifier(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapNullifier(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.mint(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.mint(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.mint(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.self(', 'statement_variable', ')', 'valid_end_line'],

    ],
    no_variable_kernel: [
        ['optional_statement_variable', 'kernel.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.checkpoint()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.checkpoint(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimContractCall(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinReceive()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinReceive(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinSpend()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapCoinSpend(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapNullifier()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.claimZswapNullifier(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.mint()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.mint(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.self()', 'valid_end_line'],
        ['optional_statement_variable', 'kernel.self(', 'random_input', ')', 'valid_end_line'],
    ],
    counter: [
        ['variable_counter'], ['no_variable_counter'],  
    ],
    variable_counter: [
        ['optional_statement_variable', 'var_counter.decrement(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.decrement(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.increment(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.increment(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.lessThan(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.read()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.read(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.read(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.lessThan(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],

    ],
    no_variable_counter: [
        ['optional_statement_variable', 'var_counter.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.decrement()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.decrement(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.increment()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.increment(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.lessThan()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.lessThan(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_counter.resetToDefault(', 'random_input', ')', 'valid_end_line'],
    ],
    set: [
        ['variable_set'], ['no_variable_set'],
    ],
    variable_set: [
        ['optional_statement_variable', 'var_set.insert(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insert(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin(bob, tom, greg, adonis)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.isEmpty(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.member(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.member(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.remove(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.remove(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.size(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_set: [
        ['optional_statement_variable', 'var_set.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insert()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insert(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.insertCoin(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.isEmpty()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.isEmpty(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.member()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.member(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.remove()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.remove(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.resetToDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.size()', 'valid_end_line'],
        ['optional_statement_variable', 'var_set.size(', 'random_input', ')', 'valid_end_line'],
    ],
    map: [
        ['variable_map'], ['no_variable_map'],
    ],
    variable_map: [
        ['optional_statement_variable', 'var_map.insert(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insert(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insert(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin(bob, tom, greg, adonis)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertDefault(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.isEmpty(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.lookup(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.lookup(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.member(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.member(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.remove(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.remove(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.size(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_map: [
        ['optional_statement_variable', 'var_map.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insert()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insert(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertCoin(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.insertDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.isEmpty()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.isEmpty(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.lookup()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.lookup(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.member()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.member(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.remove()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.remove(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.resetToDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.size()', 'valid_end_line'],
        ['optional_statement_variable', 'var_map.size(', 'random_input', ')', 'valid_end_line'],
    ],
    list: [
        ['variable_list'], ['no_variable_list'],
    ],
    variable_list: [
        ['optional_statement_variable', 'var_list.head(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.isEmpty(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.length(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.popFront(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFront(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFront(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFrontCoin(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFrontCoin(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFrontCoin(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_list: [
        ['optional_statement_variable', 'var_list.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.head()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.head(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.isEmpty()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.isEmpty(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.length()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.length(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.popFront()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.popFront(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFront()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFront(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFrontCoin()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.pushFrontCoin(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_list.resetToDefault(', 'random_input', ')', 'valid_end_line'],
    ],
    mt: [
        ['variable_mt'], ['no_variable_mt'],
    ],
    variable_mt: [
        ['optional_statement_variable', 'var_mt.checkRoot(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.checkRoot(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insert(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insert(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHash(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHash(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHashIndex(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHashIndex(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHashIndex(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndex(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndex(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndex(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndexDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndexDefault(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.findPathForLeaf(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.firstFree(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.pathFoLeaf(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.pathFoLeaf(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.pathFoLeaf(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.root(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_mt: [
        ['optional_statement_variable', 'var_mt.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.checkRoot()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.checkRoot(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insert()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insert(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHash()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHash(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHashIndex()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertHashIndex(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndex()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndex(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndexDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.insertIndexDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.resetToDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.findPathForLeaf()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.findPathForLeaf(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.firstFree()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.firstFree(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.pathFoLeaf()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.pathFoLeaf(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.root()', 'valid_end_line'],
        ['optional_statement_variable', 'var_mt.root(', 'random_input', ')', 'valid_end_line'],
    ],
    hmt: [
        ['variable_hmt'], ['no_variable_hmt'],
    ],
    variable_hmt: [
        ['optional_statement_variable', 'var_hmt.check_root(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.check_root(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insert(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insert(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHash(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHash(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHashIndex(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHashIndex(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHashIndex(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndex(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndex(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndex(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndexDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndexDefault(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.resetToDefault(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.findPathForLeaf(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.firstFree(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.history(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.pathFoLeaf(', 'statement_variable', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.pathFoLeaf(bob, tom)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.pathFoLeaf(bob, tom, greg)', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.root(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_hmt: [
        ['optional_statement_variable', 'var_hmt.', 'random_input', '()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.check_root()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.check_root(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insert()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insert(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHash()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHash(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHashIndex()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertHashIndex(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndex()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndex(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndexDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.insertIndexDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.resetToDefault()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.resetToDefault(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.findPathForLeaf()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.findPathForLeaf(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.firstFree()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.firstFree(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.history()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.history(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.pathFoLeaf()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.pathFoLeaf(', 'random_input', ')', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.root()', 'valid_end_line'],
        ['optional_statement_variable', 'var_hmt.root(', 'random_input', ')', 'valid_end_line'],
    ],
    optional_statement_variable: [['const adam = ']],
    after_statement: [
        ['no_variable_after_statement'], ['variable_after_statement'],
    ],
    variable_after_statement: [
        ['assert (', 'adam', ' ', 'statement_operator', ' ', 'statement_variable', ', ', '"check this out"', ')', 'valid_end_line'],
        ['assert (', 'adam', ' ? ', 'statement_variable', ' : ', 'statement_variable', ', ', '"check this out"', ')', 'valid_end_line'],
        ['assert (', 'adam', ' ? ', 'statement_methods', ' : ', 'statement_methods', ', ', '"check this out"', ')', 'valid_end_line'],
        ['const z = adam', ' ', 'statement_operator', ' ', 'statement_variable', 'valid_end_line'],
        ['const t = ', 'default<', 'statement_variable', '>', 'valid_end_line'],
        ['const t = ', 'disclose(', 'statement_variable', ')', 'valid_end_line'],
        ['return ', 'statement_variable', 'valid_end_line'],
        ['return ', 'disclose(', 'statement_variable', ')', 'valid_end_line'],
    ],
    no_variable_after_statement: [
        ['assert (', 'adam', ' ', 'statement_operator', ' ', 'no_variable_statement_methods', ', ', '"check this out"', ')', 'valid_end_line'],
        ['const z = ', 'no_variable_statement_methods', ' ', 'statement_operator', ' ', 'no_variable_statement_methods', 'valid_end_line'],
        ['const t = ', 'no_variable_statement_methods', 'valid_end_line'],
        ['const t = ', 'default<', 'no_variable_statement_methods', '>', 'valid_end_line'],
        ['const t = ', 'disclose(', 'no_variable_statement_methods', ')', 'valid_end_line'],
        ['return ', 'no_variable_statement_methods', 'valid_end_line'],
        ['return ', 'disclose(', 'no_variable_statement_methods', ')', 'valid_end_line'],
    ],
    statement_operator: [['||'], ['&&'], ['=='], ['!='], ['+'], ['-'], ['*'], ['<'], ['<='], ['>='], ['>']],
    statement_variable: [['tom'], ['bob'], ['greg'], ['adonis']],
    random_input: [
        ['small_random_number'],
        ['random_string'],
        ['random_version'],
        ['random_table'],
        ['[', 'random_table', ']'],
        ['random_keyword'],
    ],
    statement_valid_types: [['statement_ledger_types'], ['statement_std_types']],
    statement_std_types: [
        ['Boolean'],
        ['Field'],
        ['Uint<', '254', '>'],
        ['Uint<', '0', '..', 'small_random_number', '>'],
        ['Opaque<"string">'],
        ['Opaque<"Uint8Array">'],
        ['Bytes<', 'small_random_number', '>'],
        ['Vector<', '20', ', ', 'statement_std_types', '>'],
        ['Maybe<', 'statement_std_types', '>'],
        ['Either<', 'statement_std_types', ',', 'statement_std_types', '>'],
        ['NativePoint'],
        ['MerkleTreeDigest'],
        ['MerkleTreePathEntry'],
        ['MerkleTreePath<', '20', ',', 'statement_std_types', '>'],
        ['ContractAddress'],
        ['ShieldedCoinInfo'],
        ['QualifiedShieldedCoinInfo'],
        ['ZswapCoinPublicKey'],
        ['ShieldedSendResult'],
        ['UserAddress'],
        ['[]'],
    ],
    statement_ledger_types: [
        ['Kernel'],
        ['Counter'],
        ['List<', 'statement_std_types', '>'],
        ['Set<', 'statement_std_types', '>'],
        ['Map<', 'statement_std_types', ', ', 'statement_valid_types', '>'],
        ['MerkleTree<', '20', ', ', 'statement_std_types', '>'],
        ['HistoricMerkleTree<', '20', ', ', 'statement_std_types', '>'],
    ],
    statement_methods: [
        ['variable_statement_methods'], ['no_variable_statement_methods'],
    ],
    variable_statement_methods: [
        ['some<', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['some<', 'random_input', '>(', 'statement_variable', ')'],
        ['some<', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['none<', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['left<', 'statement_std_types', ',', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['left<', 'statement_std_types', ',', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['right<', 'statement_std_types', ',', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['right<', 'statement_std_types', ',', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['transientHash<', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['transientHash<', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['transientCommit<', 'statement_std_types', '>(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['transientCommit<', 'statement_std_types', '>(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['transientCommit<', 'statement_std_types', '>(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['transientCommit<', 'statement_std_types', '>(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['persistentHash<', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['persistentCommit<', 'statement_std_types', '>(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['persistentCommit<', 'statement_std_types', '>(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['persistentCommit<', 'statement_std_types', '>(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['persistentCommit<', 'statement_std_types', '>(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['persistentHash<', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['degradeToTransient(', 'statement_variable', ')'],
        ['degradeToTransient(', 'statement_methods', ')'],
        ['upgradeFromTransient(', 'statement_variable', ')'],
        ['upgradeFromTransient(', 'statement_methods', ')'],
        ['ecAdd(', 'statement_variable', ',', 'statement_variable', ')'],
        ['ecAdd(', 'statement_methods', ',', 'statement_variable', ')'],
        ['ecAdd(', 'statement_variable', ',', 'statement_methods', ')'],
        ['ecAdd(', 'statement_methods', ',', 'statement_methods', ')'],
        ['ecMul(', 'statement_variable', ',', 'statement_variable', ')'],
        ['ecMul(', 'statement_methods', ',', 'statement_variable', ')'],
        ['ecMul(', 'statement_variable', ',', 'statement_methods', ')'],
        ['ecMul(', 'statement_methods', ',', 'statement_methods', ')'],
        ['ecMulGenerator(', 'statement_variable', ')'],
        ['ecMulGenerator(', 'statement_methods', ')'],
        ['hashToCurve<', 'statement_std_types', '>(', 'statement_variable', ')'],
        ['hashToCurve<', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['merkleTreePathRoot<', 'small_random_number', ',', 'statement_methods', '>(', 'statement_variable', ')'],
        ['merkleTreePathRoot<', 'small_random_number', ',', 'random_input', '>(', 'statement_variable', ')'],
        ['merkleTreePathRoot<', 'small_random_number', ',', 'statement_std_types', '>(', 'statement_methods', ')'],
        ['merkleTreePathRootNoLeafHash<', 'small_random_number', '>(', 'statement_variable', ')'],
        ['merkleTreePathRootNoLeafHash<', 'small_random_number', '>(', 'statement_methods', ')'],
        ['nativeToken(', 'statement_variable', ')'],
        ['nativeToken(', 'statement_methods', ')'],
        ['tokenType(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['tokenType(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['tokenType(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['tokenType(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['mintShieldedToken(', 'statement_variable', ', ', 'statement_variable', ',', 'statement_variable', ', ', 'statement_variable', ')'],
        ['mintShieldedToken(', 'statement_methods', ', ', 'statement_variable', ',', 'statement_methods', ', ', 'statement_variable', ')'],
        ['mintShieldedToken(', 'statement_methods', ', ', 'statement_methods', ',', 'statement_methods', ', ', 'statement_methods', ')'],
        ['mintUnshieldedToken(', 'statement_variable', ', ', 'statement_variable', ',', 'statement_variable', ')'],
        ['mintUnshieldedToken(', 'statement_variable', ', ', 'statement_methods', ',', 'statement_variable', ')'],
        ['mintUnshieldedToken(', 'statement_methods', ', ', 'statement_methods', ',', 'statement_methods', ')'],
        ['evolveNonce(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['evolveNonce(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['evolveNonce(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['evolveNonce(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['shieldedBurnAddress(', 'statement_variable', ')'],
        ['shieldedBurnAddress(', 'statement_methods', ')'],
        ['receiveShielded(', 'statement_variable', ')'],
        ['receiveShielded(', 'statement_methods', ')'],
        ['receiveShielded(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['receiveUnshielded(', 'statement_variable', ')'],
        ['receiveUnshielded(', 'statement_methods', ')'],
        ['receiveUnshielded(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['sendShielded(', 'statement_variable', ', ', 'statement_variable', ',', 'statement_variable', ')'],
        ['sendShielded(', 'statement_methods', ', ', 'statement_variable', ',', 'statement_methods', ', ', 'statement_variable', ')'],
        ['sendShielded(', 'statement_methods', ', ', 'statement_methods', ',', 'statement_methods', ')'],
        ['sendUnshielded(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['sendUnshielded(', 'statement_methods', ', ', 'statement_methods', ',', 'statement_methods', ')'],
        ['sendImmediateShielded(', 'statement_variable', ', ', 'statement_variable', ',', 'statement_variable', ')'],
        ['sendImmediateShielded(', 'statement_methods', ', ', 'statement_variable', ',', 'statement_methods', ', ', 'statement_variable', ')'],
        ['sendImmediateShielded(', 'statement_methods', ', ', 'statement_methods', ',', 'statement_methods', ')'],
        ['unshieldedBalance(', 'statement_variable', ')'],
        ['unshieldedBalance(', 'statement_methods', ')'],
        ['unshieldedBalance(', 'statement_variable', 'statement_methods', ')'],
        ['unshieldedBalanceLt(', 'statement_variable', ')'],
        ['unshieldedBalanceLt(', 'statement_variable', 'statement_methods', ')'],
        ['unshieldedBalanceLt(', 'statement_variable', 'statement_variable', ')'],
        ['unshieldedBalanceLt(', 'statement_methods', 'statement_methods', ')'],
        ['unshieldedBalanceLt(', 'statement_methods', 'statement_methods', 'statement_variable', ')'],
        ['unshieldedBalanceLte(', 'statement_variable', ')'],
        ['unshieldedBalanceLte(', 'statement_variable', 'statement_methods', ')'],
        ['unshieldedBalanceLte(', 'statement_variable', 'statement_variable', ')'],
        ['unshieldedBalanceLte(', 'statement_methods', 'statement_methods', ')'],
        ['unshieldedBalanceLte(', 'statement_methods', 'statement_methods', 'statement_variable', ')'],
        ['unshieldedBalanceGt(', 'statement_variable', ')'],
        ['unshieldedBalanceGt(', 'statement_variable', 'statement_methods', ')'],
        ['unshieldedBalanceGt(', 'statement_variable', 'statement_variable', ')'],
        ['unshieldedBalanceGt(', 'statement_methods', 'statement_methods', ')'],
        ['unshieldedBalanceGt(', 'statement_methods', 'statement_methods', 'statement_variable', ')'],
        ['unshieldedBalanceGte(', 'statement_variable', ')'],
        ['unshieldedBalanceGte(', 'statement_variable', 'statement_methods', ')'],
        ['unshieldedBalanceGte(', 'statement_variable', 'statement_variable', ')'],
        ['unshieldedBalanceGte(', 'statement_methods', 'statement_methods', ')'],
        ['unshieldedBalanceGte(', 'statement_methods', 'statement_methods', 'statement_variable', ')'],
        ['mergeCoin(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['mergeCoin(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['mergeCoin(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['mergeCoin(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['mergeCoinImmediate(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['mergeCoinImmediate(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['mergeCoinImmediate(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['mergeCoinImmediate(', 'statement_methods', ', ', 'statement_methods', ')'],
        ['ownPublicKey(', 'statement_variable', ')'],
        ['ownPublicKey(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['ownPublicKey(', 'statement_methods', ')'],
        ['createZswapInput(', 'statement_variable', ')'],
        ['createZswapInput(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['createZswapInput(', 'statement_methods', ')'],
        ['createZswapOutput(', 'statement_variable', ', ', 'statement_variable', ')'],
        ['createZswapOutput(', 'statement_methods', ', ', 'statement_variable', ')'],
        ['createZswapOutput(', 'statement_variable', ', ', 'statement_methods', ')'],
        ['createZswapOutput(', 'statement_methods', ', ', 'statement_methods', ')'],
    ],
    no_variable_statement_methods: [
        ['some<', 'statement_std_types', '>()'],
        ['some<', 'statement_std_types', '>(', 'random_input', ')'],
        ['some<', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['none<', 'statement_std_types', '>()'],
        ['none<', 'statement_std_types', '>(', 'random_input', ')'],
        ['none<', 'statement_std_types', '>(', 'random_input', ')'],
        ['none<', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['left<', 'statement_std_types', ',', 'statement_std_types', '>()'],
        ['left<', 'statement_std_types', ',', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['left<', 'statement_std_types', ',', 'statement_std_types', '>(', 'random_input', ')'],
        ['right<', 'statement_std_types', ',', 'statement_std_types', '>()'],
        ['right<', 'statement_std_types', ',', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['right<', 'statement_std_types', ',', 'statement_std_types', '>(', 'random_input', ')'],
        ['transientHash<', 'random_input', '>()'],
        ['transientHash<', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['transientHash<', 'statement_std_types', '>(', 'random_input', ')'],
        ['transientHash<', 'random_input', '>(', 'statement_std_types', ')'],
        ['transientCommit<', 'statement_std_types', '>()'],
        ['transientCommit<', 'statement_std_types', '>(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['transientCommit<', 'statement_std_types', '>(', 'random_input', ', ', 'random_input', ')'],
        ['transientCommit<', 'random_input', '>(', 'statement_std_types', ', ', 'statement_std_types', ')'],
        ['persistentHash<', 'statement_std_types', '>()'],
        ['persistentHash<', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['persistentHash<', 'statement_std_types', '>(', 'random_input', ')'],
        ['persistentHash<', 'random_input', '>(', 'statement_std_types', ')'],
        ['persistentCommit<', 'statement_std_types', '>()'],
        ['persistentCommit<', 'statement_std_types', '>(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['persistentCommit<', 'statement_std_types', '>(', 'random_input', ', ', 'random_input', ')'],
        ['persistentCommit<', 'random_input', '>(', 'statement_std_types', ', ', 'statement_std_types', ')'],
        ['degradeToTransient()'],
        ['degradeToTransient(', 'no_variable_statement_methods', ')'],
        ['degradeToTransient(', 'random_input', ')'],
        ['degradeToTransient(', 'statement_std_types', ')'],
        ['upgradeFromTransient()'],
        ['upgradeFromTransient(', 'no_variable_statement_methods', ')'],
        ['upgradeFromTransient(', 'random_input', ')'],
        ['upgradeFromTransient(', 'statement_std_types', ')'],
        ['ecAdd()'],
        ['ecAdd(', 'no_variable_statement_methods', ',' ,'no_variable_statement_methods', ')'],
        ['ecAdd(', 'random_input', ',' ,'random_input', ')'],
        ['ecMul()'],
        ['ecMul(', 'statement_std_types', ',' ,'statement_std_types', ')'],
        ['ecMul(', 'no_variable_statement_methods', ',', 'no_variable_statement_methods', ')'],
        ['ecMul(', 'random_input', ',', 'random_input', ')'],
        ['ecMul(', 'statement_std_types', ',', 'statement_std_types', ')'],
        ['ecMulGenerator()'],
        ['ecMulGenerator(', 'no_variable_statement_methods', ')'],
        ['ecMulGenerator(', 'random_input', ')'],
        ['ecMulGenerator(', 'statement_std_types', ')'],
        ['hashToCurve<', 'random_input', '>()'],
        ['hashToCurve<', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['hashToCurve<', 'statement_std_types', '>(', 'random_input', ')'],
        ['hashToCurve<', 'random_input', '>(', 'statement_std_types', ')'],
        ['merkleTreePathRoot<', 'small_random_number', ',', 'random_input', '>()'],
        ['merkleTreePathRoot<', 'small_random_number', ',', 'statement_std_types', '>(', 'no_variable_statement_methods', ')'],
        ['merkleTreePathRootNoLeafHash<', 'small_random_number', '>()'],
        ['merkleTreePathRootNoLeafHash<', 'small_random_number', '>(', 'no_variable_statement_methods', ')'],
        ['merkleTreePathRootNoLeafHash<', 'small_random_number', '>(', 'random_input', ')'],
        ['nativeToken()'],
        ['nativeToken(', 'random_input', ')'],
        ['nativeToken(', 'no_variable_statement_methods', ')'],
        ['tokenType()'],
        ['tokenType(', 'random_input', ', ', 'random_input', ')'],
        ['tokenType(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['mintShieldedToken()'],
        ['mintShieldedToken(', 'random_input', ', ', 'random_input', ')'],
        ['mintShieldedToken(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ',', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['mintShieldedToken(', 'random_input', ', ', 'random_input', ',', 'random_input', ', ', 'random_input', ')'],
        ['mintUnshieldedToken()'],
        ['mintUnshieldedToken(', 'random_input', ', ', 'random_input', ')'],
        ['mintUnshieldedToken(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ',', 'no_variable_statement_methods', ')'],
        ['mintUnshieldedToken(', 'random_input', ', ', 'random_input', ',', 'random_input', ')'],
        ['evolveNonce()'],
        ['evolveNonce(', 'random_input', ')'],
        ['evolveNonce(', 'random_input', ', ', 'random_input', ')'],
        ['evolveNonce(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['shieldedBurnAddress()'],
        ['shieldedBurnAddress(', 'random_input', ')'],
        ['shieldedBurnAddress(', 'no_variable_statement_methods', ')'],
        ['receiveShielded()'],
        ['receiveShielded(', 'random_input', ')'],
        ['receiveShielded(', 'no_variable_statement_methods', ')'],
        ['receiveUnshielded()'],
        ['receiveUnshielded(', 'random_input', ')'],
        ['receiveUnshielded(', 'no_variable_statement_methods', ')'],
        ['sendShielded()'],
        ['sendShielded(', 'random_input', ', ', 'random_input', ')'],
        ['sendShielded(', 'random_input', ', ', 'random_input', ',', 'random_input', ')'],
        ['sendShielded(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ',', 'no_variable_statement_methods', ')'],
        ['sendUnshielded()'],
        ['sendUnshielded(', 'random_input', ', ', 'random_input', ')'],
        ['sendUnshielded(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['sendImmediateShielded()'],
        ['sendImmediateShielded(', 'random_input', ', ', 'random_input', ')'],
        ['sendImmediateShielded(', 'random_input', ', ', 'random_input', ',', 'random_input', ')'],
        ['sendImmediateShielded(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ',', 'no_variable_statement_methods', ')'],
        ['unshieldedBalance(', 'random_input', ')'],
        ['unshieldedBalance(', 'no_variable_statement_methods', ')'],
        ['unshieldedBalance(', 'random_input', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceLt(', 'random_input', ')'],
        ['unshieldedBalanceLt(', 'random_input', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceLt(', 'random_input', 'random_input', ')'],
        ['unshieldedBalanceLt(', 'no_variable_statement_methods', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceLte(', 'random_input', ')'],
        ['unshieldedBalanceLte(', 'random_input', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceLte(', 'random_input', 'random_input', ')'],
        ['unshieldedBalanceLte(', 'no_variable_statement_methods', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceGt(', 'random_input', ')'],
        ['unshieldedBalanceGt(', 'random_input', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceGt(', 'random_input', 'random_input', ')'],
        ['unshieldedBalanceGt(', 'no_variable_statement_methods', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceGte(', 'random_input', ')'],
        ['unshieldedBalanceGte(', 'random_input', 'no_variable_statement_methods', ')'],
        ['unshieldedBalanceGte(', 'random_input', 'random_input', ')'],
        ['unshieldedBalanceGte(', 'no_variable_statement_methods', 'no_variable_statement_methods', ')'],
        ['mergeCoin()'],
        ['mergeCoin(', 'random_input', ')'],
        ['mergeCoin(', 'random_input', ', ', 'random_input', ')'],
        ['mergeCoin(', 'random_input', ', ', 'random_input', ', ', 'random_input', ')'],
        ['mergeCoin(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['mergeCoinImmediate()'],
        ['mergeCoinImmediate(', 'random_input', ')'],
        ['mergeCoinImmediate(', 'random_input', ', ', 'random_input', ')'],
        ['mergeCoinImmediate(', 'random_input', ', ', 'random_input', ', ', 'random_input', ')'],
        ['mergeCoinImmediate(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
        ['ownPublicKey()'],
        ['ownPublicKey(', 'random_input', ')'],
        ['ownPublicKey(', 'no_variable_statement_methods', ')'],
        ['createZswapInput()'],
        ['createZswapInput(', 'random_input', ')'],
        ['createZswapInput(', 'no_variable_statement_methods', ')'],
        ['createZswapOutput()'],
        ['createZswapOutput(', 'random_input', ')'],
        ['createZswapOutput(', 'random_input', ', ', 'random_input', ')'],
        ['createZswapOutput(', 'random_input', ', ', 'random_input', ', ', 'random_input', ')'],
        ['createZswapOutput(', 'no_variable_statement_methods', ', ', 'no_variable_statement_methods', ')'],
    ],
};

exports.std_grammar = std_grammar;
